"use client";

/**
 * The Project chapter of the home blueprint motion.
 *
 * Every building line rendered here is generated by `homeBlueprintGeometry`
 * from the Owner-adopted A600 executable profile. This component chooses paint
 * and timing; it never chooses geometry, and it has no fallback drawing to fall
 * back to — if the profile seal fails, the derivation throws and nothing
 * renders.
 *
 * It is an isolated module. It does not mount itself, does not know about the
 * homepage, and takes its heading from whatever integrates it later.
 */

import { useCallback, useEffect, useId, useMemo, useRef, useState, useSyncExternalStore } from "react";
import type { CSSProperties, KeyboardEvent } from "react";

import {
  HOME_BLUEPRINT_PHASE_ORDER,
  HOME_BLUEPRINT_PROJECT_DRAWING,
  formatFeetInches,
  homeBlueprintPhaseIndex,
} from "../../lib/homeBlueprintGeometry";
import type { HomeBlueprintDrawing, HomeBlueprintPhase } from "../../lib/homeBlueprintGeometry";

import styles from "./LiveBlueprintSequence.module.css";

/** Below this width the sequence never auto-advances. */
export const COMPACT_VIEWPORT_QUERY = "(max-width: 47.999rem)";
export const REDUCED_MOTION_QUERY = "(prefers-reduced-motion: reduce)";

export type LiveBlueprintSequenceProps = {
  /** Defaults to the drawing bound to the adopted profile on `main`. */
  drawing?: HomeBlueprintDrawing;
  initialPhase?: HomeBlueprintPhase;
  /** Auto progression. Suppressed regardless on reduced motion and on mobile. */
  autoAdvance?: boolean;
  /** Id of the heading this figure belongs to, supplied by the integrator. */
  headingId?: string;
  className?: string;
};

/* ------------------------------------------------- pure sequence behaviour */

export function nextBlueprintPhase(phase: HomeBlueprintPhase): HomeBlueprintPhase {
  const next = (homeBlueprintPhaseIndex(phase) + 1) % HOME_BLUEPRINT_PHASE_ORDER.length;
  return HOME_BLUEPRINT_PHASE_ORDER[next];
}

export function previousBlueprintPhase(phase: HomeBlueprintPhase): HomeBlueprintPhase {
  const count = HOME_BLUEPRINT_PHASE_ORDER.length;
  const previous = (homeBlueprintPhaseIndex(phase) - 1 + count) % count;
  return HOME_BLUEPRINT_PHASE_ORDER[previous];
}

export type BlueprintKeyCommand =
  | { type: "select"; phase: HomeBlueprintPhase }
  | { type: "toggle" }
  | null;

/** Roving-selection keyboard map for the phase rail. */
export function resolveBlueprintKeyCommand(key: string, current: HomeBlueprintPhase): BlueprintKeyCommand {
  switch (key) {
    case "ArrowRight":
    case "ArrowDown":
      return { type: "select", phase: nextBlueprintPhase(current) };
    case "ArrowLeft":
    case "ArrowUp":
      return { type: "select", phase: previousBlueprintPhase(current) };
    case "Home":
      return { type: "select", phase: HOME_BLUEPRINT_PHASE_ORDER[0] };
    case "End":
      return { type: "select", phase: HOME_BLUEPRINT_PHASE_ORDER[HOME_BLUEPRINT_PHASE_ORDER.length - 1] };
    case "p":
    case "P":
      return { type: "toggle" };
    default:
      return null;
  }
}

export type BlueprintMotionMode = "static" | "live";

/**
 * Reveal is cumulative, so the sheet reads as a drawing being drafted rather
 * than as slides. In static mode every layer is present, which is what a
 * reduced-motion reader and a no-script reader both get.
 */
export function isLayerRevealed(
  layerPhase: HomeBlueprintPhase,
  activePhase: HomeBlueprintPhase,
  motion: BlueprintMotionMode,
): boolean {
  return motion === "static" || homeBlueprintPhaseIndex(layerPhase) <= homeBlueprintPhaseIndex(activePhase);
}

export type AutoAdvanceConditions = {
  enabled: boolean;
  playing: boolean;
  /** Pointer is over the figure, or focus is inside it. */
  interacting: boolean;
  documentHidden: boolean;
  reducedMotion: boolean;
  /** Mobile-width viewport. */
  compact: boolean;
  mounted: boolean;
};

export function shouldAutoAdvance(conditions: AutoAdvanceConditions): boolean {
  return (
    conditions.mounted &&
    conditions.enabled &&
    conditions.playing &&
    !conditions.interacting &&
    !conditions.documentHidden &&
    !conditions.reducedMotion &&
    !conditions.compact
  );
}

function cssVariables(entries: Record<string, string | number>): CSSProperties {
  return entries as CSSProperties;
}

/* ---------------------------------------------------- environment signals */

/*
 * Every environment signal is read through `useSyncExternalStore` with a server
 * snapshot of `false`. The server render and the first client render therefore
 * agree, hydration stays stable, and the sheet is complete before any of these
 * resolve.
 */

const NEVER_CHANGES = () => () => undefined;

function useHydrated(): boolean {
  return useSyncExternalStore(
    NEVER_CHANGES,
    () => true,
    () => false,
  );
}

function useMediaQuery(query: string): boolean {
  const subscribe = useCallback(
    (onChange: () => void) => {
      const media = window.matchMedia(query);
      media.addEventListener("change", onChange);
      return () => media.removeEventListener("change", onChange);
    },
    [query],
  );

  return useSyncExternalStore(
    subscribe,
    () => window.matchMedia(query).matches,
    () => false,
  );
}

function subscribeToVisibility(onChange: () => void): () => void {
  document.addEventListener("visibilitychange", onChange);
  return () => document.removeEventListener("visibilitychange", onChange);
}

function useDocumentHidden(): boolean {
  return useSyncExternalStore(
    subscribeToVisibility,
    () => document.visibilityState === "hidden",
    () => false,
  );
}

/* ----------------------------------------------------------- the component */

export default function LiveBlueprintSequence({
  drawing = HOME_BLUEPRINT_PROJECT_DRAWING,
  initialPhase = "lead",
  autoAdvance = true,
  headingId,
  className,
}: LiveBlueprintSequenceProps) {
  const reactId = useId();
  const titleId = `${reactId}-title`;
  const descriptionId = `${reactId}-description`;
  const railId = `${reactId}-rail`;

  const [activePhase, setActivePhase] = useState<HomeBlueprintPhase>(initialPhase);
  const [playing, setPlaying] = useState(true);
  const [interacting, setInteracting] = useState(false);

  const mounted = useHydrated();
  const reducedMotion = useMediaQuery(REDUCED_MOTION_QUERY);
  const compact = useMediaQuery(COMPACT_VIEWPORT_QUERY);
  const documentHidden = useDocumentHidden();

  const stepRefs = useRef<Array<HTMLButtonElement | null>>([]);

  // Server and first client render agree on `static`, so hydration is stable
  // and a reader without JavaScript keeps the complete sheet.
  const motion: BlueprintMotionMode = mounted && !reducedMotion ? "live" : "static";
  const activeIndex = homeBlueprintPhaseIndex(activePhase);
  const activeDescriptor = drawing.phases[activeIndex];

  const autoAdvanceActive = shouldAutoAdvance({
    enabled: autoAdvance,
    playing,
    interacting,
    documentHidden,
    reducedMotion,
    compact,
    mounted,
  });

  useEffect(() => {
    if (!autoAdvanceActive) {
      return;
    }

    const timer = window.setTimeout(() => {
      setActivePhase((phase) => nextBlueprintPhase(phase));
    }, drawing.phases[homeBlueprintPhaseIndex(activePhase)].holdMs);

    return () => window.clearTimeout(timer);
  }, [autoAdvanceActive, activePhase, drawing.phases]);

  const selectPhase = useCallback((phase: HomeBlueprintPhase, moveFocus: boolean) => {
    setActivePhase(phase);
    if (moveFocus) {
      stepRefs.current[homeBlueprintPhaseIndex(phase)]?.focus();
    }
  }, []);

  const handleRailKeyDown = useCallback(
    (event: KeyboardEvent<HTMLOListElement>) => {
      const command = resolveBlueprintKeyCommand(event.key, activePhase);

      if (command === null) {
        return;
      }

      event.preventDefault();

      if (command.type === "toggle") {
        setPlaying((current) => !current);
        return;
      }

      selectPhase(command.phase, true);
    },
    [activePhase, selectPhase],
  );

  const transportAvailable = autoAdvance && !reducedMotion && !compact;

  const layerStyles = useMemo(
    () =>
      new Map(
        drawing.paths.map((path, index) => [
          path.id,
          cssVariables({
            "--blueprint-length": path.length,
            "--blueprint-delay": `${(index % 12) * 55}ms`,
          }),
        ]),
      ),
    [drawing.paths],
  );

  const { recordBlock, viewBox } = drawing;
  const recordPad = 128;
  const recordLineStep = 248;
  const recordLineTop = recordBlock.y + 1080;

  return (
    <figure
      className={className === undefined ? styles.figure : `${styles.figure} ${className}`}
      data-motion={motion}
      data-phase={activePhase}
      data-chapter={drawing.chapter}
      onPointerEnter={() => setInteracting(true)}
      onPointerLeave={() => setInteracting(false)}
      onFocus={() => setInteracting(true)}
      onBlur={() => setInteracting(false)}
    >
      <div className={styles.sheet} style={{ aspectRatio: `${viewBox.width} / ${viewBox.height}` }}>
        <svg
          className={styles.drawing}
          viewBox={drawing.viewBoxAttribute}
          preserveAspectRatio="xMidYMid meet"
          role="img"
          aria-labelledby={headingId === undefined ? titleId : `${headingId} ${titleId}`}
          aria-describedby={descriptionId}
        >
          <title id={titleId}>
            {`${drawing.provenance.modelId} concept drawing, phase ${activeIndex + 1} of ${drawing.phases.length}: ${activeDescriptor.label}`}
          </title>
          <desc id={descriptionId}>{drawing.description}</desc>

          <g className={styles.linework}>
            {drawing.paths.map((path) => (
              <path
                key={path.id}
                className={styles.line}
                d={path.d}
                fill="none"
                data-kind={path.kind}
                data-mark={path.markClass}
                data-space={path.space}
                data-opening={path.openingKind}
                data-revealed={isLayerRevealed(path.phase, activePhase, motion)}
                data-focus={path.phase === activePhase}
                style={layerStyles.get(path.id)}
              />
            ))}
          </g>

          <g className={styles.annotations}>
            {drawing.dimensions.map((dimension) => (
              <g
                key={dimension.id}
                className={styles.dimension}
                data-revealed={isLayerRevealed(dimension.phase, activePhase, motion)}
                data-focus={dimension.phase === activePhase}
              >
                <path className={styles.dimensionLine} d={dimension.d} fill="none" />
                <text
                  className={styles.dimensionLabel}
                  x={dimension.labelX}
                  y={dimension.labelY}
                  transform={
                    dimension.labelRotation === 0
                      ? undefined
                      : `rotate(${dimension.labelRotation} ${dimension.labelX} ${dimension.labelY})`
                  }
                >
                  {dimension.label}
                </text>
              </g>
            ))}

            {drawing.spaceLabels.map((space) => (
              <g
                key={space.id}
                className={styles.spaceLabel}
                data-revealed={isLayerRevealed(space.phase, activePhase, motion)}
                data-focus={space.phase === activePhase}
                style={cssVariables({
                  "--blueprint-space-size": `${space.fontSize}px`,
                  "--blueprint-area-size": `${space.areaFontSize}px`,
                })}
              >
                <text className={styles.spaceName} x={space.x} y={space.y}>
                  {space.label}
                </text>
                <text className={styles.spaceArea} x={space.x} y={space.y + space.areaOffset}>
                  {space.areaLabel}
                </text>
              </g>
            ))}
          </g>

          <g
            className={styles.record}
            data-revealed={isLayerRevealed("record", activePhase, motion)}
            data-focus={activePhase === "record"}
          >
            <text className={styles.recordTitle} x={recordBlock.x + recordPad} y={recordBlock.y + 400}>
              {recordBlock.title}
            </text>
            <text className={styles.recordSubtitle} x={recordBlock.x + recordPad} y={recordBlock.y + 860}>
              {recordBlock.subtitle}
            </text>
            {recordBlock.lines.map((line, index) => (
              <g key={line.id}>
                <text className={styles.recordTerm} x={recordBlock.x + recordPad} y={recordLineTop + index * recordLineStep}>
                  {line.term}
                </text>
                <text
                  className={styles.recordValue}
                  x={recordBlock.x + recordBlock.width - recordPad}
                  y={recordLineTop + index * recordLineStep}
                  textAnchor="end"
                >
                  {line.value}
                </text>
              </g>
            ))}
          </g>
        </svg>
      </div>

      <figcaption className={styles.caption}>
        <ol className={styles.rail} id={railId} aria-label="Blueprint drafting phases" onKeyDown={handleRailKeyDown}>
          {drawing.phases.map((phase, index) => (
            <li key={phase.id} className={styles.railItem}>
              <button
                type="button"
                ref={(node) => {
                  stepRefs.current[index] = node;
                }}
                className={styles.step}
                data-active={phase.id === activePhase}
                data-reached={index <= activeIndex}
                data-project-state={phase.projectState}
                aria-current={phase.id === activePhase ? "step" : undefined}
                tabIndex={phase.id === activePhase ? 0 : -1}
                onClick={() => selectPhase(phase.id, false)}
              >
                <span className={styles.stepIndex}>{String(index + 1).padStart(2, "0")}</span>
                <span className={styles.stepLabel}>{phase.label}</span>
              </button>
            </li>
          ))}
        </ol>

        <p className={styles.phaseCaption}>{activeDescriptor.caption}</p>

        <div className={styles.footer}>
          <button
            type="button"
            className={styles.transport}
            onClick={() => setPlaying((current) => !current)}
            disabled={!transportAvailable}
            aria-controls={railId}
          >
            {!transportAvailable ? "Auto-advance off" : playing ? "Pause sequence" : "Play sequence"}
          </button>
          <p className={styles.provenance}>
            {`${drawing.provenance.modelId} · ${drawing.provenance.adoptionState} · ${drawing.provenance.maturity} · gates ${drawing.provenance.gatesReviewed} of ${drawing.provenance.gatesTotal} reviewed`}
          </p>
        </div>

        {/* The measured facts stay readable as text at every viewport, including
            the widths at which the on-sheet annotation is intentionally thinned. */}
        <p className={styles.metrics}>
          {`${formatFeetInches(drawing.metrics.footprintWidthQ16)} × ${formatFeetInches(drawing.metrics.footprintDepthQ16)} · ${drawing.metrics.grossAreaSquareFeet} sq ft · ${drawing.metrics.spaceCount} spaces · ${drawing.metrics.openingCount} openings · wall head ${formatFeetInches(drawing.metrics.wallHeadQ16)} · ridge ${formatFeetInches(drawing.metrics.ridgeQ16)}`}
        </p>

        <p className={styles.disclaimer}>{recordBlock.disclaimer}</p>
      </figcaption>
    </figure>
  );
}
